#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/../vendor/autoload.php';

use TeraBlaze\Console\Application;
use TeraBlaze\Console\Command\Command;

$app = new Application();

$app->registerController('hello', new \TeraBlaze\Console\Controller\HelpController($app));

$app->registerCommand('help', function (array $argv) use ($app) {
    $app->getPrinter()->display("usage: console hello [ your-name ]");
});

$app->runCommand($argv);